BAOBAB_VERSION=50.0
BAOBAB_SHA256=573c84f15f5f963a440500f6f43412c928ac2335f6b69dcb58f1a1fe5201024b
BAOBAB_SOURCE_URL=https://download.gnome.org/sources/baobab/50/baobab-50.0.tar.xz
BAOBAB_BUNDLE_ID=org.gnome.baobab.local
BAOBAB_APP_NAME=Baobab
BAOBAB_SIGN_IDENTITY=-
